[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "bayleys"
version = "0.3.0"
description = "Bayleys: Bayesian Library Exploration and Virtual Screening"

requires-python = ">=3.10,<3.12"

dependencies = [
    "numpy>=1.26.4,<2.0",
    "pandas>=2.3.3,<3.0",
    "scikit-learn>=1.7.2,<1.8",
    "torch>=2.13.0,<2.14",
    "gpytorch>=1.14.2,<1.15",
    "botorch>=0.17.2,<0.18",
    "gauche==0.1.6",
    "laplace-torch==0.2.2",
    "rdkit>=2026.3.1,<2027",
    "mordredcommunity==2.0.7",
    "deepchem==2.8.0",
    "datasets>=4.8.4,<5.0",
    "transformers>=5.13.0,<5.14",
    "sentencepiece>=0.2.1,<0.3",
    "peft>=0.19.1,<0.20",
    "smi-ted @ git+https://github.com/bisect-group/materials-smi-ted-fork.git",
    "umap-learn>=0.5.12,<0.6",
    "opentsne>=1.0.4,<1.1",
]